import { describe, expect, it, jest } from "@jest/globals";

import { buildItemShareUrl } from "./item-share-url";

jest.mock("expo-linking", () => ({
  createURL: jest.fn(() => "findmine://item/example"),
}));

const { createURL } = jest.requireMock("expo-linking") as {
  createURL: jest.Mock;
};

describe("buildItemShareUrl", () => {
  it("uses the configured web base URL when present", () => {
    process.env.EXPO_PUBLIC_WEB_BASE_URL = "https://findmine.example/app/";

    expect(buildItemShareUrl("abc 123")).toBe(
      "https://findmine.example/app/item/abc%20123",
    );
  });

  it("does not share Expo Metro URLs as browser links", () => {
    delete process.env.EXPO_PUBLIC_WEB_BASE_URL;
    createURL.mockReturnValueOnce("http://119.236.102.54:8081/--/item/abc");

    expect(buildItemShareUrl("abc")).toBe("findmine://item/abc");
  });

  it("keeps native scheme URLs generated by Expo", () => {
    delete process.env.EXPO_PUBLIC_WEB_BASE_URL;
    createURL.mockReturnValueOnce("findmine:///item/abc");

    expect(buildItemShareUrl("abc")).toBe("findmine:///item/abc");
  });
});
